# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g tfx-cli
    npm install
  displayName: 'npm install'

- script: |
    tfx extension create
  displayName: 'Publish'

- task: CopyFiles@2
  inputs:
    contents: '**/*.vsix'
    targetFolder: '$(build.artifactStagingDirectory)'
  displayName: Copy .vsix files to artifact staging directory

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    artifactType: 'container'
  displayName: Publish artifacts

